app.version: 0.0.1

logging.level:
    org: INFO

server.port: 8080

spring:
  datasource:
    #url: ${DB_URL}
    #username: ${DB_USER}
    #password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties.hibernate.jdbc.lob: true